config/routes.rb
TapasRails::Application.routes.draw do

  root :to => "view_packages#index"

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resque_web_constraint = lambda do |request|
    Rails.env == "development"
  end

  mount Resque::Server, at: "/resque"

  get 'browse' => 'catalog#browse'

  resources :communities
  get 'communities/:did' => 'communities#show'
  get 'communities/:did/edit' => 'communities#edit'
  post "communities/:did" => "communities#upsert"
  get 'communities' => 'communities#index'
  delete "communities/:did" => "communities#destroy"

  resources :collections
  get 'collections/:did' => 'collections#show'
  post "collections/:did" => "collections#upsert"
  get 'collections/:did/edit' => 'collections#edit'
  get 'collections' => 'collections#index'

  resources :core_files
  get 'core_files/:did/edit' => 'core_files#edit'
  get 'core_files' => 'core_files#index'

  get 'files/:did/mods' => 'core_files#mods'
  get 'files/:did/tei' => 'core_files#tei'
  get 'files/:did' => 'core_files#api_show'
  get 'core_files/:did' => 'core_files#show'
  put 'core_files/:did/reading_interfaces' => 'core_files#rebuild_reading_interfaces'
  post 'core_files/:id' => 'core_files#update'
  post 'files/:did' => 'core_files#upsert'

  get 'files/:did/html/:view_package' => 'core_files#view_package_html'

  resources :downloads, :only => 'show'

  namespace :api do
    get 'communities/:did' => 'communities#api_show'
    get 'collections/:did' => 'collections#api_show'
    get 'core_files/:did' => 'core_files#api_show'
  end
  resources :view_packages
  get 'admin/view_packages/update' => 'view_packages#run_job', as: 'update_view_packages'
  get 'api/view_packages' => 'view_packages#api_index'

  get '/admin' => 'admin#index'
  resources :pages
  resources :news_items, path: "/news"
  resources :institutions, path: "/institutions"

  get 'my_tapas' => 'users#my_tapas'
  get 'my_projects' => 'users#my_projects'
  get 'my_collections' => 'users#my_collections'
  get 'my_records' => 'users#my_records'
  get 'admin/users/new' => 'users#admin_new', as: 'admin_new_user'
  get 'admin/users/:id' => 'users#admin_show'
  post 'admin/users' => 'users#admin_create', as: 'admin_create_user'
  get 'users/:id' => 'users#profile'
  get 'mail_users' => 'users#mail_all_users', as: 'mail_users'
  post 'mail_users' => 'users#mail_all_users'
  resources :users, :only => ['index', 'edit', 'create', 'update', 'destroy']
  resources :menu_links, path: "/menu"
  post 'update_menu_order' => 'menu_links#update_menu_order'

  match '/:id' => 'pages#show', via: 'get' #must go at end since it matches on everything

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  include Discard::Model

  # associations
  belongs_to :community
  belongs_to :depositor, class_name: "User", foreign_key: "depositor_id"
  has_and_belongs_to_many :core_files
  has_many_attached :thumbnails

  # validations
  validates :depositor_id, :description, :title, presence: true
  validates :community_id, presence: true, unless: :phantom?

  # callbacks
  after_create :set_collection_access

  def set_collection_access
    self.is_public = self.community.is_public
    self.save!
  end

  def self.phantom_collection
    pid = Rails.configuration.phantom_collection_pid
    if Collection.exists?(pid)
      return Collection.find(pid)
    else
      c = Collection.new(:pid => pid).tap do |c|
        c.title = "Orphaned TEI records."
        c.depositor = "tapasrails@neu.edu"
      end

      c.save!
      return c
    end
  end

  def as_json
    fname = (thumbnail_1.label == "File Datastream" ? '' : thumbnail_1.label)

    { :project_did => (community ? community.did : ''),
      :depositor => depositor,
      :title => mods.title.first,
      :access => drupal_access,
      :thumbnail => fname,
      :description => mods.abstract.first
    }
  end

  def community
    # from Solr drupal-core worksheet notes: "sm_field_tapas_project: string; For collections and core files, this is the machine-readable name of their containing project. In practice there is only ever one string in the array;"
    # also: "Drupal SQL table "og_membership", field "gid": The Drupal node ID of the project that the collection or core file belongs to."
   self.community_id.blank? ? nil : Community.find(self.community_id)
  end

  def depositor
    self.depositor_id.blank? ? nil : User.find(self.depositor_id)
  end

  def remove_thumbnail
    self.thumbnails = []
    self.save!
  end

  private

  def update_core_files
    return true unless @drupal_access_changed

    # If this collection is now private, we have to check to see if any other
    # collection that this object's CoreFiles belong to are public.  If none
    # are, we change that CoreFile to now also be private.
    if drupal_access == 'private'
      self.descendent_records(:solr_docs).each do |solr_doc|
        unless solr_doc.any_public_collections?
          puts "Private update being run"
          core_file = CoreFile.find(solr_doc.pid)
          core_file.drupal_access = 'private'
          core_file.save!
        end
      end
    # In this case we simply change all CoreFiles that this collection has
    # to be public, because a CoreFile has the least restrictive permission
    # level set by one of its parents
    elsif drupal_access == 'public'
      self.descendent_records(:raw).each do |record|
        unless record['drupal_access_ssim'] == 'public'
          core_file = CoreFile.find(record['id'])
          core_file.drupal_access = 'public'
          core_file.save!
        end
      end
    end
  end
end

# def update_permissions
#   # TO DO: verify what this actually does and where these updated permissions are stored;
#   if self.community
#     logger.info("updating permissions")
#     com_prop = self.community.properties
#     if !com_prop.project_members.blank? && (self.mass_permissions != "public" || self.project.mass_permissions != "public")
#       com_prop.project_members.each do |p|
#         self.rightsMetadata.permissions({person: p}, 'read')
#       end
#     end
#     if self.mass_permissions == "public" && self.project.mass_permissions == "public"
#       self.project.read_users.each do |p|
#         # if its public don't put the project_members as read users
#         self.rightsMetadata.permissions({person: p}, 'none')
#       end
#     end
#     if !com_prop.project_admins.blank?
#       com_prop.project_admins.each do |p|
#         self.rightsMetadata.permissions({person: p}, 'edit')
#       end
#     end
#     if !com_prop.project_editors.blank?
#       com_prop.project_editors.each do |p|
#         self.rightsMetadata.permissions({person: p}, 'edit')
#       end
#     end
#     # if diff between project_admins + project_editors and edit_users then remove the diff
#     edits = (com_prop.project_admins + com_prop.project_editors).uniq
#     diff = self.project.clean_edit_users - edits
#     diff.each do |d|
#       self.rightsMetadata.permissions({person: d}, 'none')
#     end
#     logger.info(self.rightsMetadata.content)
#   else
#     logger.info("permissions will be updated soon")
#   end
# end

app/controllers/collections_controller.rb
class CollectionsController < CatalogController
  include ApiAccessible

  self.copy_blacklight_config_from(CatalogController)

  before_action :can_edit?, only: [:edit, :update, :destroy]
  before_action :can_read?, :only => :show
  # before_action :enforce_show_permissions, :only=>:show

  def upsert
    if params[:thumbnail]
      params[:thumbnail] = create_temp_file(params[:thumbnail])
    end

    TapasRails::Application::Queue.push TapasObjectUpsertJob.new params
    @response[:message] = "Collection upsert accepted"
    pretty_json(202) and return
  end

  def index
    @page_title = "All Collections"
    @results = Collection.order(updated_at: :desc)

    respond_to do |format|
      format.html { render :template => 'shared/index' }
      format.js { render :template => 'shared/index', :layout => false }
    end
  end

  def show
    @collection = Collection.find(params[:id])
    @page_title = @collection.title
  end

  def new
    @page_title = "Create New Collection"
    @communities = Community.joins(:community_members).where(community_members: { user_id: current_user.id, member_type: ["editor", "admin"] })
    @collection = Collection.new(community: @community)
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.depositor = current_user
    @collection.save!

    redirect_to @collection and return
  end

  def destroy
    collection = Collection.find(params[:id])
    community = collection.community

    collection.discard!

    redirect_to community
  end

  def edit
    @collection = Collection.find(params[:id])
    @communities = Community.accessible_by(current_ability)
    @page_title = "Edit #{@collection.title}"
  end

  def update
    @collection = Collection.find(params[:id])
    @collection.update(collection_params)

    redirect_to @collection and return
  end

  protected

  def can_edit?
    collection = Collection.find(params[:id])
    can? :manage, collection
  end

  def can_read?
    collection = Collection.find(params[:id])
    can? :read, collection
  end

  private

  def collection_params
    params
      .require(:collection)
      .permit(
        :community_id,
        :description,
        :is_public,
        :title,
        thumbnails: []
      )
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_data_form.html.haml
= form_for @collection do |f|
  .container-fluid
    .row
      .form-horizontal
        .form-group
          = f.label :title, "Title", class: "control-label col-md-2"
          .col-md-6
            = f.text_field :title, required: true, pattern: ".*\\S.*", class: "form-control", placeholder: "University Libraries"
        .form-group
          = f.label :description, "Description", class: "control-label col-md-2"
          .col-md-6
            = f.text_area :description, required: true, pattern: ".*\\S.*", class: "form-control", placeholder: "Brief description of the collection"
            %p.small.help-block="This field accepts plain text"
        .form-group
          = f.label :community_id, "Project", class: "control-label col-md-2"
          .col-md-6
            = f.select :community_id, options_from_collection_for_select(@communities, 'id', 'title', @collection.community), {}, { class: "form-control" }
        .form-group
          = f.label :is_public, "Public?", class: "control-label col-md-2"
          .col-md-6
            = f.check_box :is_public, { checked: true }
        .form-group
          = f.label :thumbnail, "Thumbnail", class: "control-label col-md-2"
          .col-md-6
            - if @collection.thumbnails.attached?
              =image_tag url_for(@collection.thumbnails.first)
              = f.label :remove_thumbnail, "Remove Thumbnail"
              = f.check_box "remove_thumbnail", { :checked => false }
            = f.file_field :thumbnails, accept: ".jpeg, .jpeg, .png", multiple: true, direct_upload: true


    %hr
  .form-actions
    = f.submit class: ['btn', 'btn-primary', 'btn-large'], value: 'Submit'

app/views/collections/edit.html.haml
= link_to "<< Back", collection_path(@collection), class: ['btn', 'btn-info', 'btn-large']

%h2.page-header
  = "Edit"
  %i="#{@collection.title}"

= render 'data_form'

app/views/collections/new.html.haml
= link_to "<< Back", collections_path, class: ['btn', 'btn-info', 'btn-large']

%h2.page-header New Collection
= render 'data_form'

app/views/collections/show.html.haml
- parent = @collection.community || nil

%ul.breadcrumb
  %li
    = link_to parent.title, community_path(parent)
  %li
    = @collection.title

- if can? :manage, @collection
  = link_to "Edit", edit_collection_path(@collection), class: ['btn', 'btn-info', 'btn-large']
  = link_to "Delete", collection_path(@collection), class: ['btn', 'btn-danger', 'btn-large'], method: "delete", confirm: "Are you sure you want to delete this collection?"
- records = @collection.core_files || []

%h2.page-header= @collection.title


%div.row
  %div.col-md-3
    %dt= "Project"
    %dd= link_to parent.title, parent
    - if !parent.institutions.blank?
      %dt Affiliated Institutions
      - parent.institutions.each do |i|
        - int = Institution.find(i)
        %dd
          = link_to(int.name, institution_path(int))
        %br
    - if !@collection.thumbnails.attached?
      = image_tag "tapaslogo-opaque.png"
    -else
      = image_tag url_for(@collection.thumbnails.first)
    - if !@collection.description.blank?
      %dt= "Description"
      %dd= @collection.description
    %dt= "Record Count"
    %dd= records.count


  %div.col-md-9
    %panel.panel-default.panel-records
      %div.panel-heading
        %h3.panel-title
          = "Records"
          - if can? :manage, @collection
            %small
              %a{href:new_core_file_path, class: 'pull-right'}
                %i.fa.fa-plus
                = "Add New"
      %div.panel-body
        - records.each do |record|
          %div.col-lg-3
            .record.tile
              - if can? :manage, record
                %a{href:edit_core_file_path(record), class: ['btn','btn-xs','btn-default','pull-right']}
                  %i.fa.fa-pencil
                  = "Edit"
              - if record.thumbnails.blank?
                =image_tag "tapaslogo-opaque.png"
              -else
                %img{src:record.thumbnail.download_path('thumbnail_1')}
              %h4= link_to record.title, record
              - if record.file_type != :tei_content
                %span.btn-xs.btn.btn-info
                  = "Support File"