config/routes.rb
TapasRails::Application.routes.draw do

  root :to => "view_packages#index"

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resque_web_constraint = lambda do |request|
    Rails.env == "development"
  end

  mount Resque::Server, at: "/resque"

  get 'browse' => 'catalog#browse'

  resources :communities
  get 'communities/:did' => 'communities#show'
  get 'communities/:did/edit' => 'communities#edit'
  post "communities/:did" => "communities#upsert"
  get 'communities' => 'communities#index'
  delete "communities/:did" => "communities#destroy"

  resources :collections
  get 'collections/:did' => 'collections#show'
  post "collections/:did" => "collections#upsert"
  get 'collections/:did/edit' => 'collections#edit'
  get 'collections' => 'collections#index'

  resources :core_files
  get 'core_files/:did/edit' => 'core_files#edit'
  get 'core_files' => 'core_files#index'

  get 'files/:did/mods' => 'core_files#mods'
  get 'files/:did/tei' => 'core_files#tei'
  get 'files/:did' => 'core_files#api_show'
  get 'core_files/:did' => 'core_files#show'
  put 'core_files/:did/reading_interfaces' => 'core_files#rebuild_reading_interfaces'
  post 'core_files/:id' => 'core_files#update'
  post 'files/:did' => 'core_files#upsert'

  get 'files/:did/html/:view_package' => 'core_files#view_package_html'

  resources :downloads, :only => 'show'

  namespace :api do
    get 'communities/:did' => 'communities#api_show'
    get 'collections/:did' => 'collections#api_show'
    get 'core_files/:did' => 'core_files#api_show'
  end
  resources :view_packages
  get 'admin/view_packages/update' => 'view_packages#run_job', as: 'update_view_packages'
  get 'api/view_packages' => 'view_packages#api_index'

  get '/admin' => 'admin#index'
  resources :pages
  resources :news_items, path: "/news"
  resources :institutions, path: "/institutions"

  get 'my_tapas' => 'users#my_tapas'
  get 'my_projects' => 'users#my_projects'
  get 'my_collections' => 'users#my_collections'
  get 'my_records' => 'users#my_records'
  get 'admin/users/new' => 'users#admin_new', as: 'admin_new_user'
  get 'admin/users/:id' => 'users#admin_show'
  post 'admin/users' => 'users#admin_create', as: 'admin_create_user'
  get 'users/:id' => 'users#profile'
  get 'mail_users' => 'users#mail_all_users', as: 'mail_users'
  post 'mail_users' => 'users#mail_all_users'
  resources :users, :only => ['index', 'edit', 'create', 'update', 'destroy']
  resources :menu_links, path: "/menu"
  post 'update_menu_order' => 'menu_links#update_menu_order'

  match '/:id' => 'pages#show', via: 'get' #must go at end since it matches on everything

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  attr_accessible :name, :description, :image, :address, :latitude, :longitude, :url if Rails::VERSION::MAJOR < 4
  validates_presence_of :name

  has_many :users
  has_many :communities_institutions
  has_many :communities, through: :communities_institutions
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  extend ActiveSupport::Concern
  before_action :verify_admin, :except => [:show, :index]

  rescue_from ActiveRecord::RecordNotFound do |exception|
    render_404(exception)
  end

  included do
    rescue_from ActiveRecord::RecordInvalid do |exception|
      flash[:error] = exception.to_s
      redirect_to '/admin'
    end
  end

  # cch: commenting out as ActiveFedora has been removed
  # def show
  #   @institution = Institution.find(params[:id])
  #   @page_title = @institution.name
  #   count = ActiveFedora::SolrService.count("institutions_ssim:\"#{@institution.id}\"")
  #   @communities = ActiveFedora::SolrService.query("institutions_ssim:\"#{@institution.id}\"", rows: count)
  # end

  def show
    @institution = Institution.find(params[:id])
    @page_title = @institution.name
    count = SolrService.count("institutions_ssim:\"#{@institution.id}\"")
    @communities = SolrService.query("institutions_ssim:\"#{@institution.id}\"", rows: count)
  end

  def edit
    @institution = Institution.find(params[:id])
    @page_title = @institution.name
  end

  def update
    @institution = Institution.find(params[:id])
    @page_title = @institution.name
    @institution.update_attributes(institution_params)
    if @institution.valid?
      @institution.save!
      redirect_to @institution
    else
      flash.now[:error] = @institution.errors.full_messages.join(",")
      render(:action => :edit)
    end
  end

  def new
    @page_title = "New Institution"
    @institution = Institution.new
    @users =[]
    User.all.each do |u|
      @users << [u.name, u.id]
    end
  end

  def create
    @institution = Institution.new(institution_params)
    if @institution.valid?
      @institution.save!
      redirect_to @institution
    else
      flash.now[:error] = @institution.errors.full_messages.join(",")
      render(:action => :new)
    end
  end

  def index
    @page_title = "Institutions"
    @institutions = Institution.all
    if !session[:flash_success].blank?
      flash[:success] = session[:flash_success]
      session.delete(:flash_success)
    end
  end

  def destroy
    @institution = Institution.find(params[:id])
    name = @institution.name
    redirect_to(:action => :index)
    if @institution.destroy
      session[:flash_success] = "#{name} has been deleted"
    end
  end

  private

    def verify_admin
      redirect_to root_path unless current_user&.admin?
    end

    def institution_params
      params.require(:institution).permit(:name, :description, :image, :address, :latitude, :longitude, :url)
    end
end

app/views/institutions/_data_form.html.haml
= form_for @institution do |f|
  .container-fluid
    .row
      .form-horizontal
        .form-group
          = f.label :name, "Name", class: "control-label col-md-2"
          .col-md-6
            = f.text_field :name, required: true, pattern: ".*\\S.*", class: "form-control", placeholder: "Institution Name"

            -# :image, :url
        .form-group
          = f.label :description, "Description", class: "control-label col-md-2"
          .col-md-6
            = f.text_area :description, class: "form-control", placeholder: "description"
            %p.small.help-block="This field accepts plain text"

        .form-group
          = f.label :address, "Address", class: "control-label col-md-2"
          .col-md-6
            = f.text_field :address, class: "form-control", placeholder: "address"
        .form-group
          = f.label :latitude, "Latitude", class: "control-label col-md-2"
          .col-md-6
            = f.text_field :latitude, class: "form-control", placeholder: "latitude"
        .form-group
          = f.label :longitude, "Longitude", class: "control-label col-md-2"
          .col-md-6
            = f.text_field :longitude, class: "form-control", placeholder: "longitude"


    %hr
  .form-actions
    = f.submit class: ['btn', 'btn-primary', 'btn-large'], value: 'Submit'

app/views/institutions/edit.html.haml
%ul.breadcrumb
  %li= link_to("Admin", admin_path)
  %li= link_to("Institutions", institutions_path)
  %li= "Edit \"#{@institution.name}\""
%h2.page-header
  = "Edit"
  %i="#{@institution.name}"

= render 'data_form'

app/views/institutions/index.html.haml
%h1= "Institutions"
%ul.breadcrumb
  - if current_user && current_user.admin?
    %li= link_to("Admin", admin_path)
  %li= "Institutions"
- if current_user && current_user.admin?
  =link_to "Create New Institution", new_institution_path, class:['btn', 'btn-primary', 'btn-large']
-if @institutions.length > 0
  %table.table.table-striped
    %tr
      %th
        = "Institution"
      %th
        = "Updated at"
    - @institutions.each do |institution|
      %tr
        %td
          %h3
            = link_to(institution.name, institution_path(institution.id))
            - if current_user && current_user.admin?
              %a.btn.btn-default.btn-sm{:href=>edit_institution_path(institution.id)}
                = "Edit"
              %a.btn.btn-danger.btn-sm{:href=>institution_path(institution.id), "data-method"=>"delete"}
                %i.fa.fa-trash
        %td
          = institution.updated_at
-else
  There are currently no institutions available

app/views/institutions/new.html.haml
%ul.breadcrumb
  %li= link_to("Admin", admin_path)
  %li= link_to("Institutions", institutions_path)
  %li= "New Institution"
%h2.page-header New Institution
= render 'data_form'

app/views/institutions/show.html.haml
%ul.breadcrumb
  - if current_user && current_user.admin?
    %li= link_to("Admin", admin_path)
  %li= link_to("Institutions", institutions_path)
  %li= "#{@institution.name}"
%h2.page-header
  = @institution.name
- if current_user && current_user.admin?
  = link_to "Edit", edit_institution_path(@institution), class:['btn', 'btn-info', 'btn-large']
%dl
  - if !@institution.description.blank?
    %dt= "Description"
    %dd= @institution.description
  - if !@institution.image.blank?
    %dt= "Image"
    %dd= @institution.image
  - if !@institution.address.blank?
    %dt= "Address"
    %dd= @institution.address
  - if !@institution.latitude.blank? && !@institution.longitude.blank?
    -# TODO embed map here
  - if !@institution.url.blank?
    %dt= "URL"
    %dd= link_to(@institution.url)
- if !@communities.blank?
  %panel.panel-default.panel-projects
    %div.panel-heading
      %h2.panel-title
        = "Projects"
    %div.panel-body
      %table.table
        - @communities.each do |p|
          %tr
            %td
              %h4
                = link_to(p['title_info_title_ssi'], community_path(p['id']))