config/routes.rb
TapasRails::Application.routes.draw do

  root :to => "view_packages#index"

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resque_web_constraint = lambda do |request|
    Rails.env == "development"
  end

  mount Resque::Server, at: "/resque"

  get 'browse' => 'catalog#browse'

  resources :communities
  get 'communities/:did' => 'communities#show'
  get 'communities/:did/edit' => 'communities#edit'
  post "communities/:did" => "communities#upsert"
  get 'communities' => 'communities#index'
  delete "communities/:did" => "communities#destroy"

  resources :collections
  get 'collections/:did' => 'collections#show'
  post "collections/:did" => "collections#upsert"
  get 'collections/:did/edit' => 'collections#edit'
  get 'collections' => 'collections#index'

  resources :core_files
  get 'core_files/:did/edit' => 'core_files#edit'
  get 'core_files' => 'core_files#index'

  get 'files/:did/mods' => 'core_files#mods'
  get 'files/:did/tei' => 'core_files#tei'
  get 'files/:did' => 'core_files#api_show'
  get 'core_files/:did' => 'core_files#show'
  put 'core_files/:did/reading_interfaces' => 'core_files#rebuild_reading_interfaces'
  post 'core_files/:id' => 'core_files#update'
  post 'files/:did' => 'core_files#upsert'

  get 'files/:did/html/:view_package' => 'core_files#view_package_html'

  resources :downloads, :only => 'show'

  namespace :api do
    get 'communities/:did' => 'communities#api_show'
    get 'collections/:did' => 'collections#api_show'
    get 'core_files/:did' => 'core_files#api_show'
  end
  resources :view_packages
  get 'admin/view_packages/update' => 'view_packages#run_job', as: 'update_view_packages'
  get 'api/view_packages' => 'view_packages#api_index'

  get '/admin' => 'admin#index'
  resources :pages
  resources :news_items, path: "/news"
  resources :institutions, path: "/institutions"

  get 'my_tapas' => 'users#my_tapas'
  get 'my_projects' => 'users#my_projects'
  get 'my_collections' => 'users#my_collections'
  get 'my_records' => 'users#my_records'
  get 'admin/users/new' => 'users#admin_new', as: 'admin_new_user'
  get 'admin/users/:id' => 'users#admin_show'
  post 'admin/users' => 'users#admin_create', as: 'admin_create_user'
  get 'users/:id' => 'users#profile'
  get 'mail_users' => 'users#mail_all_users', as: 'mail_users'
  post 'mail_users' => 'users#mail_all_users'
  resources :users, :only => ['index', 'edit', 'create', 'update', 'destroy']
  resources :menu_links, path: "/menu"
  post 'update_menu_order' => 'menu_links#update_menu_order'

  match '/:id' => 'pages#show', via: 'get' #must go at end since it matches on everything

end

app/views/admin/index.html.haml
%h2.page_title
  = "Admin"

%hr

%h3
  = "Static Pages"
=link_to "Create New Page", new_page_path, class:['btn', 'btn-primary', 'btn-large']
%br
=link_to "View all Pages", pages_path, class:['btn', 'btn-primary', 'btn-large']

%h3
  = "News"
=link_to "Create New News Item", new_news_item_path, class:['btn', 'btn-primary', 'btn-large']
%br
=link_to "View all News Items", news_items_path, class:['btn', 'btn-primary', 'btn-large']

%h3
  = "Institutions"
=link_to "Create New Institution", new_institution_path, class:['btn', 'btn-primary', 'btn-large']
%br
=link_to "View all Institutions", institutions_path, class:['btn', 'btn-primary', 'btn-large']

%h3
  = "View Packages"
=link_to "View all View Packages", view_packages_path, class:['btn', 'btn-primary', 'btn-large']
%br
=link_to "Run View Package Job", update_view_packages_path, class:['btn', 'btn-primary', 'btn-large']

%h3
  = "Menus"
=link_to "Manage Menus", menu_links_path, class:['btn', 'btn-primary', 'btn-large']

%h3
  = "Users"
=link_to "Create New User", new_user_invitation_path, class:['btn', 'btn-primary', 'btn-large']
%br
=link_to "View all Users", users_path, class:['btn', 'btn-primary', 'btn-large']
%br
=link_to "Send Mail to all Users", mail_users_path, class:['btn', 'btn-primary', 'btn-large']

%h3
  = "Resque Workers"
= link_to "Resque Dashboard", resque_server_path, class:['btn', 'btn-primary', 'btn-large']