config/routes.rb
TapasRails::Application.routes.draw do

  root :to => "view_packages#index"

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resque_web_constraint = lambda do |request|
    Rails.env == "development"
  end

  mount Resque::Server, at: "/resque"

  get 'browse' => 'catalog#browse'

  resources :communities
  get 'communities/:did' => 'communities#show'
  get 'communities/:did/edit' => 'communities#edit'
  post "communities/:did" => "communities#upsert"
  get 'communities' => 'communities#index'
  delete "communities/:did" => "communities#destroy"

  resources :collections
  get 'collections/:did' => 'collections#show'
  post "collections/:did" => "collections#upsert"
  get 'collections/:did/edit' => 'collections#edit'
  get 'collections' => 'collections#index'

  resources :core_files
  get 'core_files/:did/edit' => 'core_files#edit'
  get 'core_files' => 'core_files#index'

  get 'files/:did/mods' => 'core_files#mods'
  get 'files/:did/tei' => 'core_files#tei'
  get 'files/:did' => 'core_files#api_show'
  get 'core_files/:did' => 'core_files#show'
  put 'core_files/:did/reading_interfaces' => 'core_files#rebuild_reading_interfaces'
  post 'core_files/:id' => 'core_files#update'
  post 'files/:did' => 'core_files#upsert'

  get 'files/:did/html/:view_package' => 'core_files#view_package_html'

  resources :downloads, :only => 'show'

  namespace :api do
    get 'communities/:did' => 'communities#api_show'
    get 'collections/:did' => 'collections#api_show'
    get 'core_files/:did' => 'core_files#api_show'
  end
  resources :view_packages
  get 'admin/view_packages/update' => 'view_packages#run_job', as: 'update_view_packages'
  get 'api/view_packages' => 'view_packages#api_index'

  get '/admin' => 'admin#index'
  resources :pages
  resources :news_items, path: "/news"
  resources :institutions, path: "/institutions"

  get 'my_tapas' => 'users#my_tapas'
  get 'my_projects' => 'users#my_projects'
  get 'my_collections' => 'users#my_collections'
  get 'my_records' => 'users#my_records'
  get 'admin/users/new' => 'users#admin_new', as: 'admin_new_user'
  get 'admin/users/:id' => 'users#admin_show'
  post 'admin/users' => 'users#admin_create', as: 'admin_create_user'
  get 'users/:id' => 'users#profile'
  get 'mail_users' => 'users#mail_all_users', as: 'mail_users'
  post 'mail_users' => 'users#mail_all_users'
  resources :users, :only => ['index', 'edit', 'create', 'update', 'destroy']
  resources :menu_links, path: "/menu"
  post 'update_menu_order' => 'menu_links#update_menu_order'

  match '/:id' => 'pages#show', via: 'get' #must go at end since it matches on everything

end

app/models/user.rb
class User < ActiveRecord::Base
  require "net/http"
  require "uri"
  # Connects this user object to Hydra behaviors.
  # include Hydra::User
  # Connects this user object to Blacklights Bookmarks.
  include Blacklight::User

  # cch: commenting this out to allow for time to upgrade carrierwave
  # mount_uploader :avatar, AvatarUploader
  # validates_integrity_of :avatar

  if Blacklight::Utils.needs_attr_accessible?
    attr_accessible :email, :password, :password_confirmation, :name, :role, :bio, :account_type
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  delegate :can?, :cannot?, :to => :ability

  belongs_to :institution

  has_many :community_members
  has_many :communities, through: :community_members

  ROLES = %w[admin paid_user unpaid_user]

  ACCOUNT_TYPES = %w[free teic teic_inst]

  def api_key=(api_key)
    @api_key = Digest::SHA512.hexdigest api_key
    self.encrypted_api_key = @api_key
  end

  # Method added by Blacklight; Blacklight uses #to_s on your
  # user class to get a user-displayable login/identifier for
  # the account.
  def to_s
    email
  end

  def ability
    @ability ||= Ability.new(self)
  end

  def user_key
    self.id.to_s
  end

  def admin?
    return self.role.eql?('admin')
  end

  def paid_user?
    return self.role.eql?('paid_user')
  end

  def unpaid_user?
    return self.role.eql?('unpaid_user')
  end

  def self.find_by_user_key(key)
    self.send("find_by_nuid".to_sym, key)
  end

  # def forem_name
  #   self.name
  # end
  #
  # def forem_email
  #   self.email
  # end

  def check_paid_status
    # FIXME: we can't use pluot, as it's too out of date
    # re-implement this with our own Wild Apricot REST wrapper?
    return true
    # api_key = ENV['WILD_APRICOT_API_KEY']
    # aid = 66796
    # # Pluot.api_key = api_key
    # # Pluot.account_id = aid
    # logger.warn("e-Mail eq #{self.email}")
    # begin
    #   response = Pluot.contacts.filter("e-Mail eq #{self.email}")
    # rescue Faraday::ConnectionFailed => e
    #   print e
    #   return false
    # end
    # logger.warn(response)
    # if response.blank?
    #   # probably an issue where we were unable to connect with wild apricot at all
    #   return true
    # end
    # contact = response[:Contacts]
    # logger.warn(contact)
    # if !contact.blank?
    #   contact = contact[0]
    #   logger.warn(contact)
    #   if contact[:Status] && contact[:Status] == "Active"
    #     logger.warn("active")
    #     return true
    #   else
    #     logger.warn("not active")
    #     return false
    #   end
    # else
    #   logger.warn("no user found")
    #   return false
    # end
  end


  def after_database_authentication
    if !self.admin?
      if self.check_paid_status
        self.role = 'paid_user'
      else
        self.role = 'unpaid_user'
      end
    end
  end

  private

    def generate_api_key
      key = Devise.friendly_token

      @api_key = Digest::SHA512.hexdigest key

      if User.where(:encrypted_api_key => @api_key)
        generate_api_key
      else
        self.encrypted_api_key = @api_key
      end
    end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_action :verify_admin

  protected

  def verify_admin
    !current_user.admin_at.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < CatalogController

  self.copy_blacklight_config_from(CatalogController)
  before_action :check_for_logged_in_user, :only => [:my_tapas, :my_projects]
  before_action :verify_admin, :only => [:index, :show, :create, :delete, :admin_show]

  def my_tapas
    @page_title = "My TAPAS"
    @user = current_user
    @projects = five_communities
    @collections = five_collections
    @records = five_records
    render 'my_tapas'
  end

  def my_projects
    @page_title = "My Projects"
    @user = current_user
    @results = @user.communities

    render 'my_projects'
  end

  def my_collections
    @page_title = "My Collections"
    @user = current_user
    @results = Collection.kept.accessible_by(current_ability)
    render 'my_collections'
  end

  def my_records
    @page_title = "My Records"
    @user = current_user
    @results = CoreFile.kept.accessible_by(current_ability)
    render 'my_records'
  end

  def index
    @page_title = "Users"
    @users = User.order(:name, :email)
    @users = @users.where("name like ? or email like ?", "%#{params[:term]}%", "%#{params[:term]}%") if params[:term]

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render json: @users.map(&:email) }
    end
  end

  def admin_show
    @user = User.find(params[:id])
    render 'show'
  end

  def profile
    @user = User.find(params[:id])
    render 'profile'
  end

  def edit
    @user = User.find(params[:id])
    @institutions = Institution.select(:name, :id)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "#{@user.email} was updated"

    redirect_to edit_user_path(@user)
  end

  def destroy
    user = User.find(params[:id])

    if user.discarded?
      user.delete
    else
      user.discard
    end

    redirect_to users_path
  end

  def search_action_url(options = {})
    # Rails 4.2 deprecated url helpers accepting string keys for 'controller' or 'action'
    # catalog_index_path(options.except(:controller, :action))
    "/"
  end

  def mail_all_users
    if params[:subject] && params[:content]
      subj = params[:subject]
      content = params[:content]
      User.all.each do |u|
        if u.email != "tapas@neu.edu"
          Resque.enqueue(SendMailJob, u, subj, content)
        end
      end
      flash[:notice] = "Mail was sent to all users"
      redirect_to "/admin"
    else
      render "mail_all_users"
    end
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :institution_id,
      :account_type,
      :admin,
      :paid
    )
  end

  def five_communities
    @user.communities.kept.limit(5).order("RAND()")
  end

  def five_collections
    Collection
      .kept
      .accessible_by(current_ability)
      .limit(5)
      .order("RAND()")
  end

  def five_records
    CoreFile
      .kept
      .accessible_by(current_ability)
      .limit(5)
      .order("RAND()")
  end

  def check_for_logged_in_user
    redirect_to new_user_session_path if current_user.nil?
  end

  def verify_admin
    redirect_to root_path unless current_user && current_user.admin?
  end

end

app/views/users/_my_collections.html.haml
-@response = @collections
%div#sidebar{ :class =>  sidebar_classes }
  = render 'catalog/search_sidebar'
%div#content{ :class => main_content_classes }
  = render 'catalog/search_results'

app/views/users/_my_projects.html.haml
-@response = @projects
%div#sidebar{ :class =>  sidebar_classes }
  = render 'catalog/search_sidebar'
%div#content{ :class => main_content_classes }
  = render 'catalog/search_results'

app/views/users/_my_records.html.haml
-@response = @records
%div#sidebar{ :class =>  sidebar_classes }
  = render 'catalog/search_sidebar'
%div#content{ :class => main_content_classes }
  = render 'catalog/search_results'

app/views/users/admin_index.html.erb
<h1>Bulk User Actions (admin only)</h1>

<% if @users.length > 0 %>
  <%= form_with(url: admin_bulk_users_path, method: 'post') do %>
    <table class="table table-striped">
      <tr>
        <th>Restore?</th>
        <th>Delete?</th>
        <th>User</th>
        <th>Updated at</th>
        <th>Last login</th>
        <th>Role</th>
        <th>Discarded at</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= check_box_tag("restore_user_ids[#{user.id}]", user.id, false, onclick: "handleRestoreCheckBoxClickFor(#{user.id});", disabled: !user.discarded?) %>
          </td>
          <td>
            <%= check_box_tag("destroy_user_ids[#{user.id}]", user.id, false, onclick: "handleDestroyCheckBoxClickFor(#{user.id}, event, #{user.discarded?});") %>
          </td>
          <td>
            <%= link_to(user.name, user_path(user.id)) %>
          </td>
          <td>
            <%= user.updated_at %>
          </td>
          <td>
            <%= user.current_sign_in_at %>
          </td>
          <td>
            <% if user.admin? %>
              "Admin"
            <% elsif user.paid_user? %>
              "Paid user"
            <% else %>
              "Unpaid user"
            <% end %>
          </td>
          <td>
            <% unless user.discarded_at.nil? %>
              <%= user.discarded_at %>
            <% else %>
              <%= link_to "Delete", user_path(user.id),
               class: 'btn btn-danger btn-sm',
               method: :delete,
               data: { confirm: "Are you sure you want to delete #{user.email}? (They can be recovered later.)" } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
    <%= submit_tag("Restore/delete selected", class: 'btn btn-warning btn-sm') %>
  <% end %>
<% else %>
  <div class="error">
    <p>Hm, it seems like there aren't any users yet. <%= link_to "Create a user?", new_user_invitation_path %></p>
  </div>
<% end %>

app/views/users/edit.html.haml
%h2.page-header
  = "Edit"
  %i="#{@user.name}"

= form_for @user do |f|
  .container-fluid
    .row
      .form-horizontal
        .form-group
          = f.label :name, "Name", class: "control-label col-md-2"
          .col-md-6
            = f.text_field :name, required: true, class: "form-control", placeholder: "Full Name"
        .form-group
          = f.label :email, "Email", class: "control-label col-md-2"
          .col-md-6
            = f.text_field :email, required: true, class: "form-control", placeholder: "Email"
        .form-group
          = f.label :institution_id, "Institution", class: "control-label col-md-2"
          .col-md-6
            = f.select :institution_id, options_for_select(@institutions.map { |i| [i.name, i.id] }, @user.institution_id), required: true, include_blank: true
        .form-group
          = f.label :account_type, "Account Type", class: "control-label col-md-2"
          .col-md-6
            = f.select :account_type, options_for_select([['Free Account', 'free'], ['TEI-C Member Account', 'teic'], ['TEI-C Member via my institution', 'teic_inst']], @user.account_type), {}
        - if current_user.admin?
          .form-group
            = f.label :admin, "Admin?", class: "control-label col-md-2"
            .col-md-6
              .checkbox
                = f.check_box :admin, {:checked => !@user.admin_at.nil?}
          .form-group
            = f.label :paid, "Paid?", class: "control-label col-md-2"
            .col-md-6
              .checkbox
                = f.check_box :paid, {:checked => !@user.paid_at.nil?}
    %hr
  .form-actions
    = f.submit class: ['btn', 'btn-primary', 'btn-large'], value: 'Submit'

app/views/users/index.html.haml
%h1= "Users"
%ul.breadcrumb
  %li= "Users"
=link_to "Create New User", "/users/sign_up", class:['btn', 'btn-primary', 'btn-large']
-if @users.length > 0
  %table.table.table-striped
    %tr
      %th
        = "User"
      %th
        = "Updated at"
      %th
        = "Last Login"
      %th
        = "Role"
      %th
        = "Discarded at"
    - @users.each do |user|
      %tr
        %td
          %h3
            = link_to(user.name, user_path(user.id))
            - if current_user.try(:admin?)
              %a.btn.btn-default.btn-sm{:href=>edit_user_path(user.id)}
                = "Edit"
              = link_to "Delete", user_path(user.id), class: ['btn', 'btn-default', 'btn-sm', 'btn-danger'], method: :delete, data: { confirm: "Are you sure you want to delete #{user.name}?" }
        %td
          = user.updated_at
        %td
          = user.current_sign_in_at
        %td
          - if !user.admin_at.nil?
            = "Admin"
          - elsif !user.paid_at.nil?
            = "Paid user"
          - else
            = "Unpaid user"
        %td
          - unless user.discarded_at.nil?
            = user.discarded_at
            = link_to "Really delete", user_path(user.id), class: ['btn', 'btn-default', 'btn-sm', 'btn-danger'], method: :delete, data: { confirm: "Are you sure you want to delete #{user.name} for real? This record will no longer exist." }
-else
  There are currently no users available

app/views/users/mail_all_users.html.haml
- @page_title = "Send Mail to All Users"
= link_to "<< Back", "/admin", class: ['btn', 'btn-info', 'btn-large']
%h2.page-header
  Send Mail to All Users
= form_tag({controller: "users", action:"mail_all_users"}, method: "post") do
  .container-fluid
    .row
      .form-horizontal
        .form-group
          = label_tag(:subject, nil, class: "control-label col-md-2")
          .col-md-6
            = text_field_tag(:subject, nil, class: "form-control")
    .row
      .form-horizontal
        .form-group
          = label_tag(:content, nil, class: "control-label col-md-2")
          .col-md-6
            = text_area_tag(:content, nil, class: "form-control")
  .form-actions
    = submit_tag("Send", class: 'btn btn-primary btn-large')

app/views/users/my_collections.html.haml
%h2= "My Collections"
%hr
= render "my_collections"

app/views/users/my_projects.html.haml
%h2= "My Projects"
%hr
- if current_user && (current_user.paid_user? || current_user.admin?)
  %div.row
    %div.col-sm-6
      %a{href:new_community_path, class: 'btn btn-success btn-sm'}
        %i.fa.fa-plus
        = "Add New Project"
= render "my_projects"

app/views/users/my_records.html.haml
%h2= "My Records"
%hr
= render "my_records"

app/views/users/my_tapas.html.haml
%h2
  = "My TAPAS"
%hr


%div.row
  %div.col-sm-6
    %panel.panel-default.panel-projects
      %div.panel-heading
        %h2.panel-title
          = "Projects"
      %div.panel-body
        - if current_user && (current_user.paid_user? || current_user.admin?)
          %a{href:new_community_path, class: 'btn btn-success btn-sm'}
            %i.fa.fa-plus
            = "Add New"
        - else
          = "In order to create a project, you must be a member of the TEI. "
          %a{href:"/pages/choosing-account"}
            = "Join now!"
          %br
          %br
        %table.table
          - if !@projects || @projects.length < 1
            = "There are no projects yet."
          - else
            - @projects.each do |p|
              %tr
                %td
                  %h4
                    = link_to(p['title_info_title_ssi'], community_path(p['id']))
                %td
                  - if can? :manage, p
                    %a{href:edit_community_path(p['id']), class: ['btn','btn-xs','btn-default']}
                      %i.fa.fa-pencil
                      = "Edit"
        %a{href:my_projects_path, class: ['btn','btn-default']}
          = "View All"
    %br
    %panel.panel-default.panel-collections
      %div.panel-heading
        %h2.panel-title
          = "Collections"
      %div.panel-body
        - if current_user && ((@projects && @projects.length > 0) || current_user.admin?)
          %a{href:new_collection_path, class: 'btn btn-success btn-sm'}
            %i.fa.fa-plus
            = "Add New"
          %br
        %table.table
          - if !@collections || @collections.length < 1
            = "You have no collections yet."
          - else
            - @collections.each do |c|
              %tr
                %td
                  %h4
                    = link_to(c['title_info_title_ssi'], collection_path(c['id']))
                %td
                  - if can? :manage, c
                    %a{href:edit_collection_path(c['id']), class: ['btn','btn-xs','btn-default']}
                      %i.fa.fa-pencil
                      = "Edit"
        %a{href:my_collections_path, class: ['btn','btn-default']}
          = "View All"
  %div.col-sm-6
    %panel.panel-default.panel-records
      %div.panel-heading
        %h2.panel-title
          = "Records"
      %div.panel-body
        - if current_user && ((@collections && @collections.length > 0) || current_user.admin?)
          %a{href:new_core_file_path, class: 'btn btn-success btn-sm'}
            %i.fa.fa-plus
            = "Add New"
          %br
        %table.table
          - if !@records || @records.length < 1
            = "There are no collections yet."
          - else
            - @records.each do |r|
              %tr
                %td
                  %h4
                    = link_to(r['title_info_title_ssi'], core_file_path(r['id']))
                %td
                  - if can? :manage, r
                    %a{href:edit_core_file_path(r['id']), class: ['btn','btn-xs','btn-default']}
                      %i.fa.fa-pencil
                      = "Edit"
        %a{href:my_records_path, class: ['btn','btn-default']}
          = "View All"

app/views/users/profile.html.haml
%h2.page-header
  = @user.name
- if current_user && current_user == @user
  = link_to "Manage Account", edit_user_registration_path(@user), class:['btn', 'btn-info', 'btn-large']
- if @user.email
  %dt= "Email"
  %dd= @user.email
%dt= "Member Since"
%dd= @user.created_at.strftime("%D")
- if @user.bio
  %dt= "Bio"
  %dd= @user.bio
- if @user.institution
  %dt= "Institution"
  %dd= @user.institution.name
%dt= "Account Type"
%dd= @user.account_type
%dt= "Role"
%dd= @user.role

%div.row
  - if @user.avatar && @user.avatar.url
    %div.col-sm-4
      = image_tag(@user.avatar.url)

app/views/users/show.html.haml
- if current_user && current_user.admin?
  = link_to "Edit", edit_user_path(@user), class:['btn', 'btn-info', 'btn-large']
%h2.page-header
  = @user.name

%dt= "ID"
%dd= @user.id

%dt= "Name"
%dd= @user.name

%dt= "Email"
%dd= @user.email

- if @user.institution
  %dt= "Institution"
  %dd= @user.institution.name

%dt= "Created At"
%dd= @user.created_at

%dt= "Updated At"
%dd= @user.updated_at

%dt= "Currently logged in since"
%dd= @user.current_sign_in_at

%dt= "Last logged in"
%dd= @user.last_sign_in_at

%dt= "Account Type"
%dd= @user.account_type

- if @user.role
  %dt= "Role"
  %dd= @user.role.gsub("_"," ").titleize

%dt="Association Counts"
%dd="Projects - #{}"
%dd="Collections - #{}"
%dd="Records - #{}"